import type { RemoteEventAction, SceneNode } from "./catalog";

export const MAX_REMOTE_EVENT_NAME = 50;
export const MAX_REMOTE_ARGUMENT = 200;

export function remoteEventNameError(eventName: string): string | null {
  const trimmedName = eventName.trim();
  if (!trimmedName) return "Event name is required.";
  if (trimmedName.length > MAX_REMOTE_EVENT_NAME) {
    return "Event name must be 50 characters or fewer.";
  }
  if (!/^[A-Za-z0-9_]+$/.test(trimmedName)) {
    return "Event name may contain only letters, numbers, and underscores.";
  }
  return null;
}

export function sanitizeRemoteEventAction(
  raw: unknown
): RemoteEventAction | null {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return null;

  const action = raw as Record<string, unknown>;
  if (
    action.type !== "remoteEvent" ||
    typeof action.eventName !== "string" ||
    typeof action.argument !== "string"
  ) {
    return null;
  }

  const eventName = action.eventName.trim();
  if (
    remoteEventNameError(eventName) ||
    action.argument.length > MAX_REMOTE_ARGUMENT
  ) {
    return null;
  }

  return { type: "remoteEvent", eventName, argument: action.argument };
}

type RemoteEventButton = SceneNode & {
  cls: "TextButton";
  action: RemoteEventAction;
};

export function remoteEventButtons(scene: SceneNode[]): RemoteEventButton[] {
  return scene.filter(
    (node): node is RemoteEventButton =>
      node.cls === "TextButton" && node.action?.type === "remoteEvent"
  );
}

export function luauString(value: string): string {
  return `"${value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")}"`;
}

export type RemoteEventBinding = {
  eventName: string;
  variable: string;
  arguments: string[];
};

export function collectRemoteEventBindings(
  scene: SceneNode[]
): RemoteEventBinding[] {
  const bindings: RemoteEventBinding[] = [];
  const bindingByName = new Map<string, RemoteEventBinding>();

  for (const button of remoteEventButtons(scene)) {
    let binding = bindingByName.get(button.action.eventName);
    if (!binding) {
      binding = {
        eventName: button.action.eventName,
        variable: `remote${bindings.length}`,
        arguments: [],
      };
      bindings.push(binding);
      bindingByName.set(binding.eventName, binding);
    }
    if (!binding.arguments.includes(button.action.argument)) {
      binding.arguments.push(button.action.argument);
    }
  }

  return bindings;
}

export function generateServerLuau(scene: SceneNode[]): string | null {
  const bindings = collectRemoteEventBindings(scene);
  if (bindings.length === 0) return null;

  const out = [
    "-- Generated by Roblox GUI Maker",
    "-- Place this Script in ServerScriptService",
    'local ReplicatedStorage = game:GetService("ReplicatedStorage")',
    "",
    'local remotes = ReplicatedStorage:FindFirstChild("Remotes")',
    "if not remotes then",
    '\tremotes = Instance.new("Folder")',
    '\tremotes.Name = "Remotes"',
    "\tremotes.Parent = ReplicatedStorage",
    'elseif not remotes:IsA("Folder") then',
    '\terror("ReplicatedStorage.Remotes must be a Folder")',
    "end",
  ];

  for (const binding of bindings) {
    const eventName = luauString(binding.eventName);
    out.push(
      "",
      `local ${binding.variable} = remotes:FindFirstChild(${eventName})`,
      `if not ${binding.variable} then`,
      `\t${binding.variable} = Instance.new("RemoteEvent")`,
      `\t${binding.variable}.Name = ${eventName}`,
      `\t${binding.variable}.Parent = remotes`,
      `elseif not ${binding.variable}:IsA("RemoteEvent") then`,
      `\terror("ReplicatedStorage.Remotes." .. ${eventName} .. " must be a RemoteEvent")`,
      "end",
      "",
      `${binding.variable}.OnServerEvent:Connect(function(player, action)`
    );
    binding.arguments.forEach((argument, index) => {
      out.push(
        `\t${index === 0 ? "if" : "elseif"} action == ${luauString(argument)} then`,
        "\t\t-- Validate the player and action before changing game state."
      );
    });
    out.push(
      "\telse",
      `\t\twarn("Unexpected " .. ${eventName} .. " action from " .. player.Name .. ": " .. tostring(action))`,
      "\tend",
      "end)"
    );
  }

  return out.join("\n");
}
