import { describe, expect, it } from "vitest";
import type { SceneNode } from "./catalog";
import {
  MAX_REMOTE_ARGUMENT,
  MAX_REMOTE_EVENT_NAME,
  collectRemoteEventBindings,
  luauString,
  remoteEventButtons,
  remoteEventNameError,
  sanitizeRemoteEventAction,
} from "./remote-events";
import { generateServerLuau } from "./server-luau";

const button = (overrides: Partial<SceneNode> = {}): SceneNode => ({
  id: "button",
  cls: "TextButton",
  name: "Button",
  pos: { x: 0, y: 0 },
  size: { x: 1, y: 1 },
  color: "#000000",
  transparency: 0,
  cornerRadius: 0,
  zindex: 1,
  ...overrides,
});

describe("luauString", () => {
  it("escapes supported Luau string characters", () => {
    expect(luauString('path\\"\n\r\tend')).toBe('"path\\\\\\"\\n\\r\\tend"');
  });
});

describe("collectRemoteEventBindings", () => {
  it("deduplicates events and arguments in first-seen order", () => {
    const scene = [
      button({ id: "buy-sword", action: { type: "remoteEvent", eventName: "ShopAction", argument: "buy_sword" } }),
      button({ id: "ban", action: { type: "remoteEvent", eventName: "AdminAction", argument: "ban" } }),
      button({ id: "buy-shield", action: { type: "remoteEvent", eventName: "ShopAction", argument: "buy_shield" } }),
      button({ id: "buy-sword-again", action: { type: "remoteEvent", eventName: "ShopAction", argument: "buy_sword" } }),
    ];

    expect(collectRemoteEventBindings(scene)).toEqual([
      { eventName: "ShopAction", variable: "remote0", arguments: ["buy_sword", "buy_shield"] },
      { eventName: "AdminAction", variable: "remote1", arguments: ["ban"] },
    ]);
  });
});

describe("generateServerLuau", () => {
  it("returns null without RemoteEvent actions", () => {
    expect(generateServerLuau([button({ action: { type: "hideGui" } })])).toBeNull();
  });

  it("creates owned instances, validates conflicts, and connects each event once", () => {
    const code = generateServerLuau([
      button({ id: "one", action: { type: "remoteEvent", eventName: "ShopAction", argument: "buy_sword" } }),
      button({ id: "two", action: { type: "remoteEvent", eventName: "ShopAction", argument: "buy_shield" } }),
      button({ id: "three", action: { type: "remoteEvent", eventName: "AdminAction", argument: "ban" } }),
    ]);

    expect(code).toContain(
      "-- Generated by Roblox GUI Maker\n-- Place this Script in ServerScriptService"
    );
    expect(code).toContain('local ReplicatedStorage = game:GetService("ReplicatedStorage")');
    expect(code).toContain('local remotes = ReplicatedStorage:FindFirstChild("Remotes")');
    expect(code).toContain('if not remotes:IsA("Folder") then');
    expect(code).toContain('error("ReplicatedStorage.Remotes must be a Folder")');
    expect(code).toContain('local remote0 = remotes:FindFirstChild("ShopAction")');
    expect(code).toContain('remote0 = Instance.new("RemoteEvent")');
    expect(code).toContain('if not remote0:IsA("RemoteEvent") then');
    expect(code?.match(/remote0\.OnServerEvent:Connect/g)).toHaveLength(1);
    expect(code?.match(/remote1\.OnServerEvent:Connect/g)).toHaveLength(1);
    expect(code).toContain('if action == "buy_sword" then');
    expect(code).toContain('elseif action == "buy_shield" then');
    expect(code).toContain("-- Validate the player and action before changing game state.");
    expect(code).toContain(
      'warn("Unexpected " .. "ShopAction" .. " action from " .. player.Name .. ": " .. tostring(action))'
    );
    expect(code).not.toMatch(/leaderstats|Destroy\(|Kick\(/);
  });

  it("escapes arguments in generated literals", () => {
    const code = generateServerLuau([
      button({ action: { type: "remoteEvent", eventName: "ShopAction", argument: 'buy"\\\n\r\t' } }),
    ]);

    expect(code).toContain('FindFirstChild("ShopAction")');
    expect(code).toContain('action == "buy\\"\\\\\\n\\r\\t"');
    expect(code).toContain(
      'warn("Unexpected " .. "ShopAction" .. " action from " .. player.Name .. ": " .. tostring(action))'
    );
  });
});

describe("remoteEventNameError", () => {
  it.each(["ShopAction", "Admin_Action_2", "A"])(
    "accepts the valid event name %s",
    (eventName) => {
      expect(remoteEventNameError(eventName)).toBeNull();
    }
  );

  it.each(["", "   "])("requires a non-empty event name", (eventName) => {
    expect(remoteEventNameError(eventName)).toBe(
      "Event name is required."
    );
  });

  it.each(["Shop/Action", "Shop-Action"])(
    "rejects unsupported characters in %s",
    (eventName) => {
      expect(remoteEventNameError(eventName)).toBe(
        "Event name may contain only letters, numbers, and underscores."
      );
    }
  );

  it("rejects event names longer than 50 characters", () => {
    expect(remoteEventNameError("A".repeat(MAX_REMOTE_EVENT_NAME + 1))).toBe(
      "Event name must be 50 characters or fewer."
    );
  });
});

describe("sanitizeRemoteEventAction", () => {
  it("trims a valid event name and permits an empty argument", () => {
    expect(
      sanitizeRemoteEventAction({
        type: "remoteEvent",
        eventName: "  ShopAction  ",
        argument: "",
      })
    ).toEqual({
      type: "remoteEvent",
      eventName: "ShopAction",
      argument: "",
    });
  });

  it("rejects an argument longer than 200 characters", () => {
    expect(
      sanitizeRemoteEventAction({
        type: "remoteEvent",
        eventName: "ShopAction",
        argument: "x".repeat(MAX_REMOTE_ARGUMENT + 1),
      })
    ).toBeNull();
  });

  it.each([
    null,
    [],
    { type: "show", eventName: "ShopAction", argument: "buy_sword" },
    { type: "remoteEvent", eventName: 1, argument: "buy_sword" },
    { type: "remoteEvent", eventName: "ShopAction", argument: 1 },
    { type: "remoteEvent", eventName: "Shop-Action", argument: "buy_sword" },
  ])("rejects malformed actions", (raw) => {
    expect(sanitizeRemoteEventAction(raw)).toBeNull();
  });
});

describe("remoteEventButtons", () => {
  it("returns only TextButtons with RemoteEvent actions", () => {
    const remoteButton = button({
      id: "remote",
      action: {
        type: "remoteEvent",
        eventName: "ShopAction",
        argument: "buy_sword",
      },
    });
    const visibilityButton = button({
      id: "visibility",
      action: { type: "hideGui" },
    });
    const mislabeledFrame = button({
      id: "frame",
      cls: "Frame",
      action: {
        type: "remoteEvent",
        eventName: "Admin_Action_2",
        argument: "ban",
      },
    });

    const result = remoteEventButtons([
      remoteButton,
      visibilityButton,
      mislabeledFrame,
    ]);

    expect(result).toEqual([remoteButton]);
    expect(result[0].action.eventName).toBe("ShopAction");
  });

  it.each([
    { type: "remoteEvent", argument: "buy_sword" },
    { type: "remoteEvent", eventName: "ShopAction" },
    { type: "remoteEvent", eventName: " ShopAction ", argument: "buy_sword" },
    { type: "remoteEvent", eventName: "Shop-Action", argument: "buy_sword" },
    { type: "remoteEvent", eventName: "ShopAction", argument: "x".repeat(MAX_REMOTE_ARGUMENT + 1) },
  ])("ignores malformed runtime action $action", (action) => {
    const scene = [button({ action: action as SceneNode["action"] })];

    expect(() => remoteEventButtons(scene)).not.toThrow();
    expect(collectRemoteEventBindings(scene)).toEqual([]);
    expect(generateServerLuau(scene)).toBeNull();
  });
});
