import type { SceneNode } from "./catalog";
import { collectRemoteEventBindings, luauString } from "./remote-events";
import { collectTeleportPlaceIds } from "./teleports";

export function generateServerLuau(scene: SceneNode[]): string | null {
  const remoteBindings = collectRemoteEventBindings(scene);
  const teleportPlaceIds = collectTeleportPlaceIds(scene);
  if (remoteBindings.length === 0 && teleportPlaceIds.length === 0) return null;

  const out = [
    "-- Generated by Roblox GUI Maker",
    "-- Place this Script in ServerScriptService",
    'local ReplicatedStorage = game:GetService("ReplicatedStorage")',
  ];

  if (teleportPlaceIds.length > 0) {
    out.push('local TeleportService = game:GetService("TeleportService")');
  }

  if (remoteBindings.length > 0) {
    out.push(
      "",
      'local remotes = ReplicatedStorage:FindFirstChild("Remotes")',
      "if not remotes then",
      '\tremotes = Instance.new("Folder")',
      '\tremotes.Name = "Remotes"',
      "\tremotes.Parent = ReplicatedStorage",
      'elseif not remotes:IsA("Folder") then',
      '\terror("ReplicatedStorage.Remotes must be a Folder")',
      "end"
    );

    for (const binding of remoteBindings) {
      const eventName = luauString(binding.eventName);
      out.push(
        "",
        `local ${binding.variable} = remotes:FindFirstChild(${eventName})`,
        `if not ${binding.variable} then`,
        `\t${binding.variable} = Instance.new("RemoteEvent")`,
        `\t${binding.variable}.Name = ${eventName}`,
        `\t${binding.variable}.Parent = remotes`,
        `elseif not ${binding.variable}:IsA("RemoteEvent") then`,
        `\terror("ReplicatedStorage.Remotes." .. ${eventName} .. " must be a RemoteEvent")`,
        "end",
        "",
        `${binding.variable}.OnServerEvent:Connect(function(player, action)`
      );
      binding.arguments.forEach((argument, index) => {
        out.push(
          `\t${index === 0 ? "if" : "elseif"} action == ${luauString(argument)} then`,
          "\t\t-- Validate the player and action before changing game state."
        );
      });
      out.push(
        "\telse",
        `\t\twarn("Unexpected " .. ${eventName} .. " action from " .. player.Name .. ": " .. tostring(action))`,
        "\tend",
        "end)"
      );
    }
  }

  if (teleportPlaceIds.length > 0) {
    out.push(
      "",
      'local rgm = ReplicatedStorage:FindFirstChild("RGM")',
      "if not rgm then",
      '\trgm = Instance.new("Folder")',
      '\trgm.Name = "RGM"',
      "\trgm.Parent = ReplicatedStorage",
      'elseif not rgm:IsA("Folder") then',
      '\terror("ReplicatedStorage.RGM must be a Folder")',
      "end",
      "",
      'local teleportRequest = rgm:FindFirstChild("TeleportRequest")',
      "if not teleportRequest then",
      '\tteleportRequest = Instance.new("RemoteEvent")',
      '\tteleportRequest.Name = "TeleportRequest"',
      "\tteleportRequest.Parent = rgm",
      'elseif not teleportRequest:IsA("RemoteEvent") then',
      '\terror("ReplicatedStorage.RGM.TeleportRequest must be a RemoteEvent")',
      "end",
      "",
      "local allowedPlaceIds = {"
    );
    for (const placeId of teleportPlaceIds) {
      out.push(`\t[${luauString(placeId)}] = true,`);
    }
    out.push(
      "}",
      "",
      "teleportRequest.OnServerEvent:Connect(function(player, placeId)",
      '\tif typeof(placeId) ~= "string" or not allowedPlaceIds[placeId] then',
      '\t\twarn("Unexpected teleport request from " .. player.Name .. ": " .. tostring(placeId))',
      "\t\treturn",
      "\tend",
      "",
      "\tlocal numericPlaceId = tonumber(placeId)",
      "\tif not numericPlaceId then return end",
      "\tlocal success, message = pcall(function()",
      "\t\tTeleportService:TeleportAsync(numericPlaceId, { player })",
      "\tend)",
      "\tif not success then",
      '\t\twarn("Teleport to " .. placeId .. " failed: " .. tostring(message))',
      "\tend",
      "end)"
    );
  }

  return out.join("\n");
}
