import { expect, test } from "@playwright/test";

test("@smoke keeps initially hidden layers off the canvas until selected", async ({
  page,
}) => {
  await page.goto("/editor?template=main-menu");

  const settingsPanel = page.locator('[data-node-id="tpl-4"]');
  await expect(settingsPanel).toHaveCount(0);

  await page.getByRole("button", { name: "Hierarchy" }).click();
  await page.locator('[data-tree-node="tpl-4"] > [role="treeitem"]').click();
  await expect(settingsPanel).toBeVisible();

  await page.locator('[data-tree-node="tpl-7"] > [role="treeitem"]').click();
  await expect(settingsPanel).toBeVisible();
  await expect(page.locator('[data-node-id="tpl-7"]')).toBeVisible();
});

test("@smoke edits and previews a secure Teleport action", async ({ page }) => {
  const consoleErrors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") consoleErrors.push(message.text());
  });

  await page.goto("/");
  await expect(page).toHaveTitle(
    "Free Online Roblox GUI Maker | Visual UI Builder"
  );
  await expect(page.locator('meta[name="description"]')).toHaveAttribute(
    "content",
    /responsive designs, preview interactions, and export Luau, JSON, and ZIP/
  );
  await expect(
    page.getByRole("heading", { level: 1, name: "Roblox GUI Maker" })
  ).toBeVisible();
  for (const heading of [
    "Responsive Layout",
    "Interaction Preview",
    "Server-Safe Actions",
    "ZIP + JSON Export",
  ]) {
    await expect(
      page.getByRole("heading", { level: 3, name: heading })
    ).toBeVisible();
  }
  const structuredData = (
    await page.locator('script[type="application/ld+json"]').allTextContents()
  ).map(
    (value) =>
      JSON.parse(value) as { "@type": string; [key: string]: unknown }
  );
  const webAppSchema = structuredData.find(
    (value) => value["@type"] === "WebApplication"
  );
  expect(JSON.stringify(webAppSchema)).toContain(
    "Browser-local ZIP project export"
  );
  expect(JSON.stringify(webAppSchema)).toContain(
    "Server handlers for RemoteEvent and Teleport actions"
  );
  const faq = page.getByRole("region", {
    name: "Frequently asked questions",
  });
  await expect(faq.locator("summary")).toHaveCount(6);
  await faq.getByText("Does the editor generate game logic?").click();
  await expect(
    faq.getByText(
      /Secure economy, purchase, reward, permission, and datastore validation/
    )
  ).toBeVisible();
  const faqSchema = structuredData.find(
    (value) => value["@type"] === "FAQPage"
  ) as {
    mainEntity?: Array<{
      name: string;
      acceptedAnswer: { text: string };
    }>;
  };
  expect(faqSchema.mainEntity).toHaveLength(6);
  expect(
    faqSchema.mainEntity?.find(
      (item) => item.name === "Is Roblox GUI Maker free to use?"
    )?.acceptedAnswer.text
  ).toBe(
    "Yes. The editor is free, requires no account, and keeps project work in your browser unless you download it."
  );

  await page.goto("/editor");
  await page.evaluate(() => window.localStorage.clear());
  await page.reload();

  await expect(page.getByLabel("Client Luau code")).toContainText(
    "-- Generated by Roblox GUI Maker"
  );
  const actionSelect = page.locator("select").filter({
    has: page.locator('option[value="teleport"]'),
  });
  await actionSelect.selectOption("teleport");

  const placeId = page.getByRole("textbox", {
    name: "Destination Place ID",
  });
  await placeId.fill("12345678901234");
  await expect(page.getByLabel("Client Luau code")).toContainText(
    'teleportRequest:FireServer("12345678901234")'
  );

  await page.getByRole("tab", { name: "Server" }).click();
  await expect(page.getByLabel("Server Luau code")).toContainText(
    '["12345678901234"] = true'
  );
  await expect(page.getByLabel("Server Luau code")).toContainText(
    "TeleportService:TeleportAsync(numericPlaceId, { player })"
  );

  await placeId.fill("01");
  await expect(page.getByText("Place ID cannot start with zero.")).toBeVisible();
  await expect(page.getByLabel("Server Luau code")).toContainText(
    '["12345678901234"] = true'
  );
  await expect(page.getByLabel("Server Luau code")).not.toContainText(
    '["01"] = true'
  );

  await placeId.fill("456");
  await page.getByRole("button", { name: "Preview" }).click();
  await page.locator('[data-node-id="play"]').click();
  await expect(page.getByRole("status")).toHaveText(
    "Teleport to Place 456. Preview does not run live teleports."
  );

  expect(
    await page.evaluate(() => ({
      innerWidth: window.innerWidth,
      scrollWidth: document.documentElement.scrollWidth,
    }))
  ).toEqual({ innerWidth: 1280, scrollWidth: 1280 });
  expect(consoleErrors).toEqual([]);
});
